
use_frameworks!

target 'IOS11AppStoreClone' do
pod 'IGListKit', '~> 3.0'
pod 'SnapKit', '~> 3.2.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
